CREATE TABLE user_infos(
    id INT NOT NULL AUTO_INCREMENT,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(40) NOT NULL,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE doc_infos(
    id INT NOT NULL AUTO_INCREMENT,
    status INT NOT NULL DEFAULT 1,
    header VARCHAR(100) NOT NULL DEFAULT "",
    content VARCHAR(2048) NOT NULL DEFAULT "",
    creator INT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX (status)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE order_infos(
    id INT NOT NULL AUTO_INCREMENT,
    status INT NOT NULL DEFAULT 1,
    count INT NOT NULL DEFAULT 0,
    name VARCHAR(40) NOT NULL,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX (status)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE order_details(
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL DEFAULT 0,
    order_id INT NOT NULL DEFAULT 0,
    order_num INT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX (order_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;